/**
 * Single source of user-facing copy for the Mini Program.
 *
 * The Mini Program ships one locale (Simplified Chinese) because WeChat is the
 * only host; the PWA keeps its own i18n resources for the browser surfaces.
 * Wording is kept in step with the PWA's `zh` locale so the two clients read the
 * same, which is why some labels differ from a literal Mini Program phrasing.
 */
export const copy = Object.freeze({
  app: {
    name: "OpenTrip",
    signInFailed: "登录失败",
    signInFailedHint: "请检查网络后重试。",
    retry: "重试",
    loading: "加载中",
    loadFailed: "加载失败",
    save: "保存",
    cancel: "取消",
    confirm: "确定",
    delete: "删除",
    edit: "编辑",
    add: "添加",
    saved: "已保存",
  },
  trips: {
    title: "行程",
    subtitle: "从下一次出发，到每一段值得留下的路。",
    createTitle: "新建行程",
    createCta: "新建行程",
    empty: "还没有行程",
    emptyHint: "创建第一个行程，开始规划路线、投票与分摊花费。",
    filterAll: "全部",
    filterActive: "进行中",
    filterPlanning: "规划中",
    filterSettled: "已结束",
    filterEmpty: "这个分类里还没有行程。",
    filterEmptyHint: "换个筛选看看，或者新建一段行程。",
    filterShowAll: "查看全部",
    openActive: "继续旅程",
    openPlanning: "继续规划",
    openSettled: "回看旅程",
    titleFromDestination: "之旅",
    optional: "待定",
    fieldDestination: "目的地",
    fieldDestinationPlaceholder: "东京、京都…",
    destinationHint: "行程名称会根据目的地生成，之后可以修改。",
    fieldStartDate: "开始日期",
    fieldDayCount: "天数",
    fieldPartySize: "人数",
    fieldBudget: "预算",
    fieldCurrency: "货币",
    createFailed: "创建行程失败",
    stopCount: "个地点",
    statusActive: "进行中",
    statusPlanning: "规划中",
    statusSettled: "已结算",
  },
  today: {
    title: "今天",
    subtitle: "不一定正在旅行，也可以安排今天、准备下一次出发，或收好上一段旅程。",
    quickCaptureTitle: "此刻发生了什么？",
    quickCaptureHint: "先写下来。标题可以在记录时补充。",
    quickCaptureAction: "开始写",
    currentTrip: "当前行程",
    recentEntries: "最近记录",
    empty: "今天不在旅途中",
    emptyHint: "也可以只安排好今天。",
    emptyAction: "规划下一次出发",
    focusTripTitle: "继续今天的旅程",
    focusTripHint: "打开当前行程，确认路线、时间和同行事项。",
    focusTripAction: "回到行程",
    focusPrepareTitle: "为下一次出发做一点准备",
    focusPrepareHint: "打开即将开始的行程，确认日期、路线和待办。",
    focusPrepareAction: "继续准备",
    focusReflectionTitle: "把刚结束的旅程收好",
    focusReflectionHint: "回想一个最想留下的瞬间，把它写成游记。",
    focusReflectionAction: "写旅后感想",
    focusHomeTitle: "给今天留一个落点",
    focusHomeHint: "写下今天的计划，或者整理一段刚结束的旅途感想。",
    focusHomeAction: "写下今天",
    weatherUnavailable: "天气暂时不可用",
    feelsLike: "体感温度",
    humidity: "湿度",
    wind: "风速",
  },
  journal: {
    title: "游记",
    subtitle: "把旅途里的地点和当时的心情，慢慢写成故事。",
    empty: "从一个小片段开始",
    emptyHint: "不用写成长文。一个瞬间、一家店，或一句当时的心情，都值得留下。",
    emptyCta: "记录第一篇",
    compose: "写游记",
    fieldTitle: "标题",
    titlePlaceholder: "标题（可选）",
    fieldBody: "正文",
    localOnly: "本机草稿",
    untitled: "无标题记录",
    deleteConfirm: "删除这篇游记？",
    notFound: "找不到这篇游记",
  },
  trip: {
    tabMap: "地图",
    tabSchedule: "日程",
    tabReservations: "预订",
    tabBudget: "预算",
    invite: "邀请",
    inviteCopyHint: "链接已复制，粘贴给同行的人即可。",
    agent: "助手",
    notFound: "找不到这个行程",
    readOnly: "你没有编辑权限",
  },
  schedule: {
    addDay: "添加一天",
    deleteDay: "删除这一天",
    deleteDayConfirm: "删除这一天及其地点？",
    addStop: "添加地点",
    stopName: "地点名称",
    stopTime: "时间",
    stopDuration: "时长",
    stopArea: "区域",
    stopCategory: "类型",
    stopCost: "花费",
    stopNote: "备注",
    free: "免费",
    emptyDay: "这一天还没有安排",
    perPerson: "/ 人",
    vote: "投票",
    comments: "评论",
    commentsEmpty: "评论 — 开启讨论",
    commentPlaceholder: "添加评论…",
    more: "更多",
    moveUp: "上移",
    moveDown: "下移",
    moveToDay: "移动到某天",
    moveToDayTitle: "移动到第几天",
    saveFailed: "保存失败",
  },
  reservations: {
    empty: "还没有预订",
    emptyHint: "把确认信息放在行程旁，所有同行者都能随时找到。",
    addTitle: "添加预订",
    fieldType: "类型",
    fieldStatus: "状态",
    fieldTitle: "名称",
    fieldProvider: "供应方",
    fieldConfirmation: "确认编号",
    fieldStartAt: "开始时间",
    fieldLocation: "地点",
    fieldNotes: "备注",
    cancelReservation: "取消预订",
    cancelConfirm: "取消这个预订？",
    typeFlight: "航班",
    typeAccommodation: "住宿",
    typeRestaurant: "餐厅",
    typeRail: "铁路",
    typeGroundTransport: "地面交通",
    typeActivity: "活动",
    typeOther: "其他",
    statusTentative: "待确认",
    statusConfirmed: "已确认",
    statusCancelled: "已取消",
    statusCompleted: "已完成",
  },
  budget: {
    total: "行程总计",
    perPerson: "人均",
    expenses: "花费",
    balances: "结余",
    paid: "已付",
    share: "应摊",
    settlements: "结算",
    empty: "还没有花费",
    emptyHint: "记录一笔花费，自动算出谁该付给谁。",
    addTitle: "添加花费",
    fieldDescription: "这笔花费用于？",
    fieldAmount: "金额",
    fieldPayer: "付款人",
    fieldParticipants: "分摊给",
    paidByPrefix: "由",
    paidBySuffix: "支付",
    splitCount: "人分摊",
    each: "每人",
    settleHint: "应付给",
    everyonePaid: "结清后互不欠款。",
  },
  map: {
    unavailable: "地图不可用",
    locate: "导航",
    allDays: "全部日期",
    pick: "在地图上选择地点",
    noLocatedStops: "还没有带坐标的地点",
    noLocatedStopsHint: "在日程里添加地点并选点，就会出现在这张地图上。",
  },
  agent: {
    title: "行程助手",
    empty: "助手会安静地关注这次行程。@agent 可以向它提问。",
    placeholder: "聊聊这次行程…（@agent 让助手回复）",
    send: "发送",
    disabled: "助手未启用",
    thinking: "思考中…",
    suggestionTitle: "助手建议",
    apply: "批准",
    dismiss: "拒绝",
    // One-shot suggested @agent draft built from create-trip intake (PWA
    // parity: zh/agent.json seed.*). {{placeholders}} are interpolated by
    // pages/trip/lib/buildAgentSeedMessage.ts.
    seedMessage: "@agent 帮我创建一个行程：{{details}}。",
    seedJoiner: "，",
    seedPartDestination: "目的地{{destination}}",
    seedPartDays: "共{{count}}天",
    seedPartDates: "{{start}}至{{end}}",
    seedPartStart: "从{{start}}开始",
    seedPartBudget: "预算{{amount}}",
    seedPartBudgetWithCurrency: "预算{{amount}} {{currency}}",
    seedPartParty: "{{count}}人",
  },
  invite: {
    title: "邀请",
    join: "加入行程",
    joining: "正在加入",
    invitedBy: "邀请人",
    memberCount: "位成员",
    expired: "邀请已过期",
    revoked: "邀请已失效",
    emailRestricted: "该邀请仅限指定邮箱",
    alreadyMember: "你已经是成员",
    roleEditor: "你将以编辑者身份加入。",
    roleViewer: "你将以查看者身份加入。",
    expiresPrefix: "过期时间 ",
    openTrip: "打开行程",
    blockedAction: "查看我的行程",
    missingToken: "邀请链接无效",
  },
  settings: {
    title: "设置",
    profile: "个人资料",
    name: "昵称",
    avatar: "头像",
    avatarHint: "可使用微信头像与昵称一键填充",
    avatarTooLarge: "头像不能超过 2MB",
    avatarUploadFailed: "头像上传失败，请重试",
    currency: "默认货币",
    about: "关于",
    environment: "环境",
    webHint: "在浏览器中打开 OpenTrip 可使用完整地图与更多登录方式。",
  },
  categories: {
    Sight: "观光",
    Food: "餐饮",
    Stay: "住宿",
    Shopping: "购物",
    Activity: "活动",
    Walk: "步行",
    Park: "公园",
    Transit: "交通",
    Plan: "计划",
  },
});
